name = "Creative Call"
author = "Jinser Kafka"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5211219016b4f968c8b5a747d82df779f6d5caa0bc1820a4e599a31a1dfd0905"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
